apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-web-app-build.yaml
  - git-version.yaml
  - build-pack.yaml
  # - yaml-lint.yaml
  - podtato-head-task.yaml
  - podtato-head-build.yaml
  - canary-rollout.yaml
  - rabbitmq.yaml
  - kyverno.yaml
  - git-clone.yaml
  - grype.yaml