apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline
  namespace: tekton-runs
secrets:
  - name: github-deimoscloud

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
      tekton.dev/git-0: https://github.com/deimoscloud
  name: github-deimoscloud
  namespace: tekton-runs
type: kubernetes.io/basic-auth
stringData:
  username: dooshima-gbamwuan-deimos
  password: *****

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: podtato-head-build
  namespace: tekton-runs
spec:
  description: "The pipeline will build the podtato-head application and push it to the local container registry"
  params:
    - name: repo
      description: The git repo
      default: https://github.com/DeimosCloud/dooshima-cicd.git     #https://github.com/dooshima-gbamwuan-deimos/podtato-head 
    - name: revision
      description: The git revision to use
      default: main
  tasks: 
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: "true"
        - name: depth
          value: "0"
      workspaces:
        - name: output
          workspace: source
    - name: git-version
      taskRef:
        name: git-version
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: branch
          value: $(params.revision)
  
    - name: build-podtatohead
      taskRef:
        name: buildpacks
      runAfter:
        - git-version
      params:
        - name: SOURCE_SUBPATH
          value: src/podtato-head-main/podtato-head-server
        - name: APP_IMAGE
          value: registry.kube-system.svc.cluster.local:80/podtato-head:$(tasks.git-version.results.packageVersion)
        - name: BUILDER_IMAGE
          value: paketobuildpacks/builder:base
      workspaces:
        - name: source
          workspace: source


    # - name: podtato-head-build
    #   taskRef:
    #       name: kaniko
    #   runAfter:
    #         - git-version
    #   params:
    #     - name: IMAGE
    #       value: registry.kube-system.svc.cluster.local:80/podtato-head:$(tasks.git-version.results.packageVersion)
    #     - name: DOCKERFILE
    #       value: src/podtato-head-main  #src/podtato-head-main/podtato-head-server
    #     - name: CONTEXT
    #       value: src/podtato-head-main/podtato-head-server   #src/podtato-head-main/podtato-head-server
    #     - name: DESTINATION
    #       value: registry.kube-system.svc.cluster.local:80/podtato-head:$(tasks.git-version.results.packageVersion)
    #     - name: SOURCE_SUBPATH
    #       value: src/podtato-head-main/podtato-head-server
    #     - name: APP_IMAGE
    #       value: registry.kube-system.svc.cluster.local:80/podtatohead:$(tasks.git-version.results.packageVersion)
    #     - name: BUILDER_IMAGE
    #       value: gcr.io/kaniko-project/executor:v1.5.1 #gcr.io/kaniko-project/executor:v1.14.0-debug
    #   workspaces:
    #     - name: source
    #       workspace: source
    - name: scan-podtatohead-app
      taskRef:
        name: grype
        kind: Task
      runAfter:
        - build-podtatohead
      params:
        - name: ARGS
          value:
            - registry.kube-system.svc.cluster.local:80/podtato-head:$(tasks.git-version.results.packageVersion)
  results:
    - name: version
      description: the version of the containers
      value: $(tasks.git-version.results.packageVersion)
  workspaces:
    - name: source


---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: 'true'
  generateName: test-podtato-head-build-
  labels:
    app.kubernetes.io/instance: gitops-tekton-annotations
  name: test-podtato-head-build
  namespace: tekton-runs
spec:
  pipelineRef:
    name: podtato-head-build
  serviceAccountName: github-deimoscloud
  timeout: 1h0m0s
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              # storage: 100Mi
              storage: "2Gi"




























# apiVersion: tekton.dev/v1beta1
# kind: Pipeline
# metadata:
#   name: podtato-head-build
#   namespace: tekton-runs
# spec:
#   description: >-
#     The pipeline will build the podtato-head application and push it to the local container registry
#   params:
#     - name: repo
#       description: The git repo
#       value: https://github.com/dooshima-gbamwuan-deimos/podtato-head.git
#     - name: revision
#       description: The git revision to use
#       value: main
#   tasks:
#     - name: git-clone
#       taskRef:
#         name: git-clone
#       params:
#         - name: url
#           value: $(params.repo)
#         - name: revision
#           value: $(params.revision)
#         - name: deleteExisting
#           value: "true"
#         - name: depth
#           value: "0"
#       workspaces:
#         - name: output
#           workspace: source
#     - name: git-version
#       taskRef:
#         name: git-version
#       runAfter:
#         - git-clone
#       workspaces:
#         - name: source
#           workspace: source
#       params:
#         - name: branch
#           value: $(params.revision)
#     - name: podtato-head-build
#       taskRef:
#         name: podtato-head-task
#       runAfter:
#         - git-version
#       params:
#         - name: SOURCE_SUBPATH

#         - name: APP_IMAGE
#           value: registry.kube-system.svc.cluster.local:80/podtato-head:$(tasks.git-version.results.packageVersion)
#         - name: BUILDER_IMAGE
#           value: paketobuildpacks/builder:base
