apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      annotationSelector: deimos.io/environment-development notin (deploy)
    patch: |
      $patch: delete
      kind: Application
      metadata:
        name: DOES NOT MATTER
  - path: node-web-app.yaml
resources:
  - ../base
  - loadgenerator.yaml
  - node-web-app.yaml
  - loadgenerator-values.yaml
  - node-web-app-values.yaml
