apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/container.allow-tags: regexp:^development-(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
    argocd-image-updater.argoproj.io/container.update-strategy: latest
  name: loadgenerator
  namespace: argocd
spec:
  source:
    helm:
      releaseName: loadgenerator
      values: |
        fullnameOverride: loadgenerator
        image:
          repository: localhost:5000/loadgenerator
          tag: latest
        livenessProbe: {}
        podAnnotations:
            instrumentation.opentelemetry.io/inject-sdk: observability/instrumentation
        readinessProbe: {}
        service:
          port: 8089

