command:
  - /cnb/process/web
extraEnvVarsConfigMaps:
  - node-web-app-env
fullnameOverride: node-web-app
image:
  repository: localhost:5000/node-web-app
  tag: 0.0.1
livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
nameOverride: node-web-app
podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: observability/instrumentation
readinessProbe:
  httpGet:
    path: /healthz
    port: 8081
service:
  port: 8081
versionOverride: 0.1.0
