apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/container.update-strategy: semver
  name: loadgenerator
  namespace: argocd
spec:
  source:
    helm:
      releaseName: loadgenerator
      values: |
        fullnameOverride: loadgenerator
        image:
          repository: localhost:5000/loadgenerator
          tag: latest
        livenessProbe: {}
        podAnnotations:
            instrumentation.opentelemetry.io/inject-sdk: observability/instrumentation
        readinessProbe: {}
        service:
          port: 8089

    # helm:
    #   valueFiles:
    #     - ../../environments/overlays/local/loadgenerator-values.yaml
