apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  deimos.io/application: myapp
  deimos.io/customer: deimos.io
  deimos.io/owner: sre@deimos.io
  deimos.io/project: dooshima-cicd-project
  deimos.io/repo: https://github.com/DeimosCloud/dooshima-cicd
  deimos.io/version: 0.0.1
resources:
  - deimos.io
  - node-web-app.yaml
  # - loadgenerator-values.yaml
  # - node-web-app-values.yaml
  - loadgenerator.yaml
  - rabbitmq-cluster-operator.yaml
  - rabbitmq.yaml
  - tekton.yaml
  - podtato-head.yaml
