
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    deimos.io/environment-local: deploy
  name: podtato-head-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dooshima-cicd-project
  source:
    repoURL: https://github.com/DeimosCloud/dooshima-cicd.git
    path: src/podtato-head-main/delivery/chart
    targetRevision: HEAD
    helm:
      releaseName: podtatohead
      # values: |
      #   fullnameOverride: podtatohead
      #   image:
      #     repository: localhost:5000/podtatohead
      #     tag: latest
      #   livenessProbe: {}
      #   podAnnotations:
      #       instrumentation.opentelemetry.io/inject-sdk: observability/instrumentation
      #   readinessProbe: {}
      #   service:
      #     port: 9090
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
  # postSync:
  #   resources:
  #     - apiVersion: argoproj.io/v1alpha1
  #       kind: Rollout
  #       name: podtatohead-rollout
  #       namespace: myapp
